### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Koshi-Y** [Koshi-Y/furima-35423#9]
# URL
https://furima-35423.herokuapp.com/
# Basic認証のIDとパスワード
ID：koshi    
Pw：2989
# 出品者用のメールアドレスとパスワード
Email:    tamazarashi@icloud.com
Pw:        azarashi2989
# 購入者用のメールアドレスとパスワード
Email:     test@test.er
Pw:         0a0a0a0a

**Comment by takumi0530** [comment]
@Koshi-Y さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [x] **issueに記載されたHerokuのURLにアクセスし、同じくissueに記載されたIDとパスワードを入力すると、最終課題アプリ（FURIMA）が表示されること**

現在、いただいているBasic認証のIDとパスワードを打ち込んでもログインできない状態です。ご確認をお願い致します。
**※上記により、動作確認ができておりません。次回ご提出時に改めて確認させていただきます。**

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Koshi-Y** [comment]
修正しました！確認をお願いします。

**Comment by takumi0530** [comment]
@Koshi-Y さん、お待たせいたしました。再度ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **クレジットカード決済ができること**
正しい情報を入力しても「Token can't be blank」と出てしまい、決済ができませんでした。
<img width="424" alt="スクリーンショット 2021-05-21 12 58 47" src="https://user-images.githubusercontent.com/76197191/119080077-65910280-ba34-11eb-898a-e3303571cad3.png">

**※上記により、購入機能と売却後の動作確認ができておりません。次回ご提出時に確認させていただきます。**


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Koshi-Y** [comment]
修正しました

**Comment by Koshi-Y** [comment]
修正しました！
確認をお願いします。

**Comment by snkw-works** [comment]
@Koshi-Y さん、ご提出ありがとうございます‼︎
修正が確認でき、問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/119091625-52882d80-ba48-11eb-8c5a-347979122877.png)
